---
- name: Install and start Apache  
  hosts: all
  sudo: yes
  
  tasks:
    - name: Install Apache
      yum: name=httpd state=present

    - name: Enable Apache Service
      service: name=httpd enabled=yes state=started